Import all of the required packages

In [2]:
import sympy as sy
import numpy as np
from numpy import linalg as LA
import scipy as sp
import math

assign an array and try to bring it to reduced row echelon form

In [83]:
a = np.array([[0, 1], [1, 0]], dtype=float)
# a = np.array([[3, 1], [2, 2]], dtype=float)
a_rref = sy.Matrix(a).rref()

print(a)
print(a_rref)
print()

v = np.array([1, -1], dtype=float)
w = np.array([-1, 1], dtype=float)

[[0. 1.]
 [1. 0.]]
(Matrix([
[1, 0],
[0, 1]]), (0, 1))



# Inner Product

In [4]:
def inner(a, b):
    return np.matmul(a, b.T)

print("INNER")
print(inner(a[:, 0], a[:, 0]))
print(np.dot(a[:, 0], a[:, 0]))
print()

INNER
17.0
17.0



# Norm

In [5]:
def norm(a):
    length = 0;
    for col in a.T:
        length += inner(col, col)
    return math.sqrt(length)

print("NORM")
print(norm(a))
print(LA.norm(a))
print()

NORM
4.69041575982343
4.69041575982343



# Angle and Orthogonality

In [6]:
def angle(a, b):
  num = np.dot(a, b)
  denom = LA.norm(a) * LA.norm(b)
  print(num / denom)
  print(np.arccos(num / denom))
  print(math.degrees(np.arccos(num / denom)))
  return math.degrees(np.arccos(num / denom))

print(a)
angle(a[:, 0], LA.inv(a)[:, 0])
angle(v, w)

-0.7592566023652966
2.432966381462123
139.39870535499554
-0.9999999999999998
3.1415926325163688
179.99999879258172


179.99999879258172

# Orthonormal Basis

In [48]:
# will not return the correct value. we need svd
def ob(a):
  left = np.matmul(a, a.T)
  b = np.concatenate([left, a]).T
  ob = sy.Matrix(b).rref()[0]
  red = np.array(ob).astype(np.float64)
  start = math.floor(red.shape[1]/2)
  end = red.shape[1]
  return red[:, start:end]

print(a)
print(ob(a))
ob = sp.linalg.orth(a)
print(ob)
# orthogonal basis is 0 for all vectors except for the same column
print(np.dot(a[:, 0], ob[:, 1]))
print(np.dot(a[:, 1], ob[:, 0]))
print(np.dot(a[:, 0], ob[:, 0]))


[[0. 1.]
 [1. 0.]]
[[0. 1.]
 [1. 0.]]
[[ 0. -1.]
 [-1.  0.]]
0.0
0.0
-1.0


# Orthogonal Complement

In [95]:
# a = np.array([[1, -1], [2, 0]])
a = np.array([[1, 2], [2, 4]])
print(a.T)
b = [0., 0.]
print(sp.linalg.null_space(a))

[[1 2]
 [2 4]]
[[-0.89442719]
 [ 0.4472136 ]]
